### ISSUE TITLE
Random user logout

### ISSUE THREAD

**Issue by ValentaTomas** [magiclabs/magic-js#165]
### ✅ Prerequisites

- [x] Did you perform a cursory search of open issues? Is this question already asked elsewhere?
- [x] Are you reporting to the correct repository (`magic-sdk`)?

### ❓ Question

We are using magic in an Electron app and the user is sometimes randomly logged out. We are unable to replicate the error, but it keeps happening. We already checked our code, but it is possible that the error is there.

We found several things that are not clear and that may be the cause:

#### Re-authenticating users
In the [magic documentation](https://docs.magic.link/client-sdk/web/examples/reauthenticating-users) it is not clear how long the session lasts and when we have to re-authenticate. 
- Does it always expire after 7 days if no other action happens?
- Is the `magic.user.isLoggedIn()` or `magic.user.getIdToken()` causing the actual re-authentication? Will this reauthentication provision a new `didToken`?

#### `didToken` claims
We have looked at the decoded claims from the `didToken` and the `ext` field was always only 15 minutes in the future. Even after waiting for 15 minutes the user was still logged in - `magic.user.isLoggedIn()` is returning `true`.
- How does this work? Is the `didToken` used solely as an "access token" and you are storing the actual information authentication information used for generating these tokens in the IndexedDB?
- Where can we see how long until the current user's session expires and he needs to log in again?

The Electron environment also does not seems to be the problem. The IndexedDB where you are storing the sessions are persistent in Electron and even deleting the application cache does not log out the user.

### 🌎 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| `magic-sdk`      | 4.0.2
| Browser          | Electron
| `yarn`           |
| Operating System | macOS 11.1

**Comment by smithki** [comment]
> How does this work? Is the didToken used solely as an "access token" and you are storing the actual information authentication information used for generating these tokens in the IndexedDB?

The DID token is not an access token; think of it as more of a self-sovereign identity token or "authentication token" to your service. DID tokens are ultimately just proof to you that the user knows their private key. Accordingly, a user's DID token does not grant further access to Magic's DKM (**delegated key management**) for other signing actions.

> Is the `magic.user.isLoggedIn()` or `magic.user.getIdToken()` causing the actual re-authentication? Will this reauthentication provision a new didToken?

`magic.user.isLoggedIn` will return `true` if the user is able to sign DID tokens. In other words, this lets you know if the user has an active session with Magic's DKM. Unless you're building a [Web3 application](https://docs.magic.link/blockchains/ethereum), it's usually better to manage your own session after authenticating the user with Magic.

A typical flow goes like this:

1. Client-side calls `magic.auth.loginWithMagicLink() => DIDToken`
2. Client-side calls server-side `/login` endpoint with `DIDToken` encoded in the `authorization` header.
3. Server-side validates `DIDToken` using the [Admin SDK of your choice](https://docs.magic.link/#server-side-admin-sdk).
4. Upon successful validation of `DIDToken`, **server-side creates an encrypted session cookie called `session`** and attaches it to the response headers.

Now, for any endpoint that requires authenticated access (like `/user` for example), your server middlewares can check for the existence the `session` cookie, validate it, and proceed! Otherwise, raise a `401`!

For a Browser / Electron / NodeJS use-case, I think you'll find our [Express / React example](https://github.com/magiclabs/example-react-express) is an easy-to-understand implementation for this idea.

Also, `magic.user.getIdToken()` will return a new DID token that your service can use to authenticate a user; it does not restart or refresh the user's session with Magic.

> We have looked at the decoded claims from the didToken and the ext field was always only 15 minutes in the future. Even after waiting for 15 minutes the user was still logged in - magic.user.isLoggedIn() is returning true.

To reiterate, the DID token is an authentication token that represents the user's identity for your service, it's not associated to the user session with Magic's DKM. By the way, you can customize the `ext` timestamp by providing an integer argument to `magic.user.getIdToken` as seconds. 900s or 15m is the default.

> How does this work? Is the didToken used solely as an "access token" and you are storing the actual information authentication information used for generating these tokens in the IndexedDB?

It's not an access token (sorry to harp on this, I just want to answer each question you asked individually).

> Where can we see how long until the current user's session expires and he needs to log in again?

We don't currently surface this information, but we'd like to in the future. For a more predictable session management experience, I recommend rolling your own sessions as described above!

**Comment by ValentaTomas** [comment]
Thanks for an exhaustive answer! :D

I will take the time to go over everything.

The session management does sound like something that is used pretty much every time you will be using magic. We are not sending the `didToken` with each request - we plan to use JWT exchanged for the `didToken`.

**Comment by smithki** [comment]
> we plan to use JWT exchanged for the didToken.

This is the way 😉

**Comment by ValentaTomas** [comment]
We did solve it by doing something similar to what you are demonstrating in the [Express / React examples](https://github.com/magiclabs/example-react-express) - by adding a refresh/access token which the client gets in exchange for the `didToken`.

The misconception was that we thought the `didToken` is used as an access token for authorized access to resources. It also looked like you "refresh" the `didToken` by using the client's magic SDK, which would be handling the persistence of the session.

**Comment by smithki** [comment]
> The misconception was that we thought the didToken is used as an access token for authorized access to resources. It also looked like you "refresh" the didToken by using the client's magic SDK, which would be handling the persistence of the session.

This is good feedback for us. We are always working to improve our documentation and dev experience. Thanks for sharing.

**Comment by terrierscript** [comment]
I got same question and find this issue.
But currently [Express / React example](https://github.com/magiclabs/example-react-express)  not implemented exchange JWT.

JWT exchange implementation removed this commit.
https://github.com/magiclabs/example-react-express/commit/0abb4e8b889f38bcd53e6b9ded1142fc28a6229e

Do you know why this is removed?

**Comment by hcote** [comment]
Hey @terrierscript, I had removed the JWT from the guide to rely on Magic for sessions and tracking if the user is logged in primarily to simplify the example. I'll add a new guide to site ASAP specifically on Magic + JWT for session management.

**Comment by hcote** [comment]
@terrierscript here's the new guide for custom sessions w JWT https://magic.link/posts/magic-jwt
