### ISSUE TITLE
Rollbar integration triggers Brave browser's Trackers and Ads shield

### ISSUE THREAD

**Issue by newbyca** [magiclabs/magic-js#192]
### ✅ Prerequisites

- [x] Did you perform a cursory search of open issues? Is this bug already reported elsewhere?
- [x] Are you running the latest SDK version?
- [x] Are you reporting to the correct repository (`magic-sdk`)?

### 🐛 Description

A simple react app with magic integration works as expected in Chrome, but not in Brave. Brave blocks a call to api.rollbar.com which seems to interrupt the app's "isLoggedIn" flow (ie, calling `magic.user.isLoggedIn()`).

### 🧩 Steps to Reproduce

1. Clone, config, and run https://github.com/sa-ma/react-magic-link-test
2. Open Chrome to localhost:3000. Login. Refresh page.
3. Open Brave to localhost:3000. Login. Refresh page.

### 🤔 Expected behavior

Expect both browser's to be logged in.

### 😮 Actual behavior

Only Chrome is logged in. Brave, instead, shows a login screen.

### 💻 Code Sample

https://github.com/sa-ma/react-magic-link-test

### 🌎 Environment

yarn: 1.22.11
magic sdk: magic-sdk@4.4.0
Chrome: Version 92.0.4515.131 (Official Build) (x86_64)
Brave: Version 1.27.109 Chromium: 92.0.4515.115 (Official Build) (x86_64)

<img width="1113" alt="Screen Shot 2021-08-04 at 9 01 53 PM" src="https://user-images.githubusercontent.com/1134341/128277334-612eb7ea-0193-450b-bdef-673c6c02da3d.png">

**Comment by smithki** [comment]
Rollbar is a logging service we use to track errors in the Magic iframe app which supports this SDK. This will trigger a warning from Brave shields, but is not responsible for issues related to session persistence. Unfortunately, session persistence in Brave, with shields up, is problematic for local development environments because `localhost:xxxx` and `auth.magic.link` (the iframe) are cross-origin. We have a workaround for production environments that utilizes a CNAME record in your DNS to circumvent the strict privacy requirements imposed by Brave. **This is not a long-term solution** and our team is currently working on an improved session persistence mechanism that should work across all modern browsers consistently.

Until then, if your use-case warrants the CNAME approach described above, you can reach out to our support via https://magic.link

**Comment by newbyca** [comment]
Thanks for the explanation @smithki
