### ISSUE TITLE
Should Magic and Social login return different wallet addresses for the same email?

### ISSUE THREAD

**Issue by mateus-batista** [magiclabs/magic-js#262]
### ✅ Prerequisites

- [✅ ] Did you perform a cursory search of open issues? Is this question already asked elsewhere?
- [✅ ] Are you reporting to the correct repository (`magic-sdk`)?

### ❓ Question

Should Magic and Social login return different wallet addresses for the same email?

When logging in with Magic link and Social login with the same email, I get two different wallet addresses (in my case, Polygon).

I'd expect the same email address to return the same wallet address regardless of the login method.

### 🌎 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| `magic-sdk`      | 7.0.0
| Browser          | Google Chrome Version 97.0.4692.71 (Official Build) (x86_64)
| `yarn`           | 1.22.10
| Operating System | macOS Monterey 12.0.1

**Comment by smithki** [comment]
Early on, we made a consequential design decision to map login types (i.e.: Google, Apple, Facebook, Email Link, SMS, WebAuthn, etc.) to separate accounts ("users"), such that each login type maps to a unique Ethereum key. The same is true for different blockchains/networks as well. For your purposes though, only the ETH key matters as that is what we use to sign DID tokens.

Now, why did we make this decision? One part to reduce the complexity of our system, and one part _security_. If we surface the same key for a **social login user** as we do for an **email link user**, we are implicitly trusting the OAuth provider to have _securely_ verified the email address for that user. We have no way to validate (and continuously audit) the security of OAuth providers we connect to, so what's stopping a malicious party from creating a spam account for a legit user that has a known email link connection within a Magic client? A practical example:

1. Bob creates an account on `app.crypto-thing.xyz` using the **email link** flow with `bob@magic.link`
2. Let's assume `app.crypto-thing.xyz` is vulnerable to a dictionary attack, making it possible for an evildoer — Sally — to know that `bob@magic.link` is a known account.
3. Sally notices that `app.crypto-thing.xyz` also supports OAuth login via "popular social network" for which Bob doesn't own an account.
4. Sally creates a spam account on "popular social network" using `bob@magic.link`.
5. Now, Sally can log into `app.crypto-thing.xyz` using "popular social network" and successfully drains all of Bob's funds because the key is equal between social login & email link.

It's very much an edge case, but a serious flaw nonetheless. Even if the OAuth provider somehow trustfully communicates to Magic that a user's email is _unverified_, we'd have to finagle some way to handle indeterminate behavior related to how keys are surfaced. Or worse, block users from logging in if they haven't yet verified their email with that OAuth provider. Neither is a great experience for users or developers. Our current approach, though more limited, is predictable, determinate, and secure.

Our goal is to support some form of automatic account linking in the future, but we simply haven't found the right trade-offs between UX and DX to move forward. Once we nail it, you will _definitely_ hear about it because we'll advertise it loudly and widely, to be sure!

For housekeeping purposes, I'm going to close this issue, but feel free to use this thread for follow-up questions & feedback!

**Comment by mateus-batista** [comment]
Hi @smithki - It makes total sense, thanks for your quick and detailed reply.

We've been using magic at the company in a bunch of different projects it just works it's awesome!

Keep the great work!

**Comment by smithki** [comment]
In case it helps, our off-the-shelf login form contains some naive logic to help guide users to the previously-used login method on a page. It's not perfect, and surely comes with its own trade-offs, but it's a pretty damn login form. Check it out: https://magic.link/docs/login-form

**Comment by mateus-batista** [comment]
We'll check it out, but probably implement some logic on our side to guide users toward their previously-used login method. Again, thanks for the quick and detailed reply ❤️
