### ISSUE TITLE
Add the Login Form Modal/Overlay to the SDK

### ISSUE THREAD

**Issue by Adamj1232** [magiclabs/magic-js#281]
### ✅ Prerequisites

- [x ] Did you perform a cursory search of open issues? Is this feature already requested elsewhere?
- [ x] Are you reporting to the correct repository (`magic-sdk`)?

### ✨ Feature Request
It would be very helpful to have the Magic Login overlay/modal form found here https://magic.link/docs/login-form
I was told through the support chat that it is only available to add through script tag. This wouldnt be a problem except the required `data-redirect-uri` prop that forces a page change.

## 🧩 Context

I work at Blocknative and we are working on integrating Magic into our Onboard V2 package. 
We currently fully support Fortmatic and it would be nice if that same level of SDK support was available through Magic

## 💻 Examples

https://magic.link/docs/login-form

<img width="404" alt="Screen Shot 2022-02-10 at 11 00 32 AM" src="https://user-images.githubusercontent.com/24457880/153491114-c405a418-f37d-47fd-bb92-442aee9ab4d0.png">

**Comment by techgangboss** [comment]
+1, we have users asking for Magic wallet support and this is a blocker

**Comment by Adamj1232** [comment]
Can we revisit this feature request? It would be great if the Magic Login form was exposed through the SDK and didn't require a redirect to allow for users to use all of the login methods without building each one custom.

**Comment by jadbox** [comment]
We'd also be interested in this support!

**Comment by am-hernandez** [comment]
Hi @Adamj1232 ,

The login form is meant to deliver a no-code/low-code solution. For other projects we have our SDK for which customization is completely open. 

A considerable amount of time has passed since this issue was created, would you let me know if you are still interested? This is a fine feature request and although we were not able to add it to our roadmap previously I will raise it again for discussion.
