### ISSUE TITLE
Should different websites return different wallet address for same email

### ISSUE THREAD

**Issue by itseasy21** [magiclabs/magic-js#330]
### ✅ Prerequisites

- [x] Did you perform a cursory search of open issues? Is this question already asked elsewhere?
- [x] Are you reporting to the correct repository (`magic-sdk`)?

### ❓ Question
This is completely regarding the web3 wallet provided by magic-sdk. 

#### Scenario:
There is a nft marketplace that supports magic SDK login and user login using the magic link with email abcd1@gmail.com and gets the wallet address `0xabcd`
Now user goes to the second nft marketplace that also supports magic link login and logins there with the same email abcd1@gmail.com but this time gets a different wallet address `0xpqrs`

I'd expect the same email address to return the same wallet address regardless of the website where the user logins if the login method is the same 

### 🌎 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| `magic-sdk`      |  8.1.1
| Browser          |  Any (Chrome | Edge | Safari)
| `yarn`           | v3.2.0
| Operating System | Any

**Comment by am-hernandez** [comment]
Hello @itseasy21 and thank you for submitting this issue.

You are experiencing expected behavior. The wallets created via **Magic Auth** are scoped to the application and are not globally available. When one app utilizes **Magic Auth** login a wallet address will be generated for the user. If that same user goes to another application using their same login credentials, with this other app also utilizing **Magic Auth** login, a new wallet will be generated.

Magic has another product releasing soon, [**Magic Connect**](https://magic.link/connect), that would exhibit the behavior you were expecting.
