### ISSUE TITLE
Magic Auth not working on Microsoft Edge, OK on Chrome/Firefox/Safari/Vivaldi

### ISSUE THREAD

**Issue by Colhodm** [magiclabs/magic-js#456]
### ✅ Prerequisites

- [ ] Did you perform a cursory search of open issues? Is this bug already reported elsewhere?
- [ ] Are you running the latest SDK version?
- [ ] Are you reporting to the correct repository (`magic-sdk`)?

### 🐛 Description

Hey Magic Team,
We have a very standard flow in our app that we use to sign users in using a magic link. It currently works for users on chrome/safari/vivaldi/firefox. Recently we onboarded a customer who uses edge, and they have been having issues.

The observed pattern in Edge is that after entering their email, verifying from their email, our web app moves them to a new page(the cookies get set), but then throws the following errors from magic.link: 
<img width="704" alt="Pasted Graphic 1" src="https://user-images.githubusercontent.com/19936058/219177370-2bcaa44b-2fa5-419b-bb79-76783b6a211d.png">

The payload of the failed HTTP requests in the screenshot are the following:
{"data":{},"error_code":"auth_relayer/UNABLE_TO_REFRESH_SESSION","message":"Unable to refresh user session. Please log in using the magic link flow to enable session persistence.","status":"failed"}
{"data":{},"error_code":"AUTH_PASSWORDLESS_LOGIN_NOT_VERIFIED","message":"Passwordless login is not verified yet","status":"failed"}

if the user refreshes, then everything works alright, but after they login & are redirected, but before they have refreshed the page, the authentication fails. We again only see this on Edge.

With some more testing realized the following, everything works if the Edge user has _basic_ mode selected, but if they have the middle or right mode, it doesn't work

<img width="914" alt="IMG_6964" src="https://user-images.githubusercontent.com/19936058/219188520-0df30f8f-4486-4336-af37-78f1a60af81b.png">

edge://settings/privacy (or type this into edge)

### 🧩 Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

### 🤔 Expected behavior

[What you expected to happen?]

### 😮 Actual behavior

[What actually happened? Please include any error stack traces you encounter.]

### 💻 Code Sample

[If possible, please provide a code repository, gist, code snippet or sample files to reproduce the issue.]

### 🌎 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| `magic-sdk`      | 8.1.1
| Browser          | Edge Version 110.0.1587.41 (Official build) (x86_64)
| `yarn`           | 8.15.0 (NPM) 1.22.10 (YARN)
| Operating System | MacOS, although bug is happening on Windows

**Comment by am-hernandez** [comment]
Hello,

Thank you for posting this issue.

The errors and warning you shared are expected when the user is not yet logged in. Checking for a valid session when there isn't one will produce the `400` on the `session/refresh` endpoint because a session doesn't exist. The warnings are fine, you can't refresh the session because there isn't a valid session. 

The final series of errors logged to the console are from polling the `status` endpoint while the app waits for the user to finish authentication. That means the user already received the login email with a magic link or OTP and the app is waiting for the user to enter the OTP or click the magic link.

By the way, I tested out session persistence on Microsoft Edge and sessions persisted normally.
