### ISSUE TITLE
User metadata retrieved `undefined`

### ISSUE THREAD

**Issue by LizanLycan** [magiclabs/magic-js#506]
### ✅ Prerequisites

- [ ] Did you perform a cursory search of open issues? Is this bug already reported elsewhere?
- [ x ] Are you running the latest SDK version?
- [ x ] Are you reporting to the correct repository (`magic-sdk`)?

### 🐛 Description

When I want to retrieve the `email` from user metadata, it returns `undefined` 

### 🧩 Steps to Reproduce

1. Install latest `magic-sdk`
2. Try to connect with UI (magic link connect)
3. Get a success connection response from Google Authentication connection.
4. Try to call `getMetadata()` method.
5. See `email` as `undefined`

### 🤔 Expected behavior

At least I want to see the `email` field of the user in the retrieves metadata.

### 😮 Actual behavior

Email and phone number fields retrieved in `undefined`

### 💻 Code Sample

`await magic.user.getMetadata()`

### 🌎 Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| `magic-sdk`      | 17.1.3
| Browser          | Edge | CHrome | Safari | Brave
| `yarn`           | 1.22.15
| Operating System | macOS 13.3.1

**Comment by am-hernandez** [comment]
Hello @LizanLycan , thank you for posting this issue!

Users may be able to hide sharing their email address from their social account which is probably why you are not seeing an email for certain users that login with a social provider like Google. If this is happening with your account you may check your account settings in Google.

[Here's a demo for the Google login](https://yvivxh.csb.app/) that logs the `magic.user.getMetadata()` result to the console after a successful login. Please give it a try (plug your API key in first). When I log in I am able to see my email address in the metadata as well as the return data from the call to `magic.oauth.getRedirectResult()`. I tried with three different Google accounts and all of them show my email address in the metadata returned from `magic.user.getMetadata()`.

Would you please share a codesandbox with this issue reproduced? You may fork the codesandbox demo I shared and make it your own!

**Comment by am-hernandez** [comment]
@LizanLycan Sorry but I answered your question as if you had a Magic Auth app. Since you are using Magic Connect you just need to request the user's email with `magic.wallet.requestUserInfoWithUI()`. This will show a modal asking the user to share their email address with your app. After the user has consented to sharing their email address with your app any subsequent calls to `magic.user.getMetadata()` will contain the user's email address in the metadata object.

You may try [this demo](https://codesandbox.io/s/magic-connect-demo-q1jqo1?file=/index.html:772-791). Simply plug in your Magic Connect API key into `index.html` line 19. Then click the purple `connectWithUI` button to connect. After login click the purple `requestUserInfoWithUI` button to request the user share their email address. After that flow is complete you can click the green `getMetadata` button to get the user metadata containing the user's email address.

Please let me know if you are still experiencing the issue after checking out the demo above!

**Comment by am-hernandez** [comment]
@LizanLycan The `magic.user.getMetadata()` method will be deprecated and removed from the Magic SDK in version 18 so I suggest you instead use `magic.wallet.getInfo()` to get the same metadata object.

**Comment by LizanLycan** [comment]
Excellent! Good suggestion! Thanks!
